import type { Metadata } from "next";
import LegalLayout from "@/components/LegalLayout";
import { brand } from "@/lib/brand";

export const metadata: Metadata = { title: "Terms of Service" };

function H({ children }: { children: React.ReactNode }) {
  return <h2 className="font-display text-lg text-text-primary">{children}</h2>;
}

export default function TermsPage() {
  return (
    <LegalLayout title="Terms of Service" updated="July 2026">
      <section className="flex flex-col gap-2">
        <H>Eligibility</H>
        <p>
          {brand.name} is for users 18 years of age or older. By using the app you confirm you
          meet this requirement.
        </p>
      </section>

      <section className="flex flex-col gap-2">
        <H>Not medical, dietetic, or professional advice</H>
        <p>
          {brand.name}’s body scan, workout plans, nutrition guidance, and coach chat are
          AI-generated, informational tools meant for motivation and general fitness guidance.
          They are not medical advice, a diagnosis, a body-composition assessment, or a
          substitute for a doctor, registered dietitian, physical therapist, or certified
          trainer. Always consult a qualified professional before making significant changes
          to your exercise or diet, especially if you have an existing health condition, are
          pregnant, or are recovering from an injury.
        </p>
      </section>

      <section className="flex flex-col gap-2">
        <H>AI limitations</H>
        <p>
          Responses are generated by a large language model and can be incomplete, generic, or
          occasionally wrong. Use your judgment, and stop any exercise that causes pain. See{" "}
          <a href="/legal/how-ai-works" className="underline underline-offset-2">
            How the AI works
          </a>{" "}
          for more detail.
        </p>
      </section>

      <section className="flex flex-col gap-2">
        <H>Acceptable use</H>
        <p>
          Don’t use {brand.name} to upload photos of anyone but yourself without consent,
          to attempt to extract or reverse engineer the underlying AI systems, to abuse rate
          limits or automate excessive requests, or for any unlawful purpose.
        </p>
      </section>

      <section className="flex flex-col gap-2">
        <H>Your data</H>
        <p>
          In local-first mode, your profile, plans, and history are stored on your device, and
          you control export and deletion at any time from Settings. See the{" "}
          <a href="/legal/privacy" className="underline underline-offset-2">
            Privacy Policy
          </a>{" "}
          for details.
        </p>
      </section>

      <section className="flex flex-col gap-2">
        <H>No warranty, limitation of liability</H>
        <p>
          {`${brand.name} is provided “as is” without warranties of any kind. To the fullest extent permitted by law, ${brand.name} is not liable for any injury, loss, or damage arising from use of the app, including reliance on AI-generated guidance.`}
        </p>
      </section>

      <section className="flex flex-col gap-2">
        <H>Changes</H>
        <p>We may update these terms as the product evolves. Continued use means you accept the current version.</p>
      </section>

      <section className="flex flex-col gap-2">
        <H>Contact</H>
        <p>{brand.supportEmail}</p>
      </section>
    </LegalLayout>
  );
}
